spring:
  aop:
    auto: true
  datasource:
    username: root
    password: p@ssw0rd
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 注意：对应实体类的路径
  type-aliases-package: com.example.seckill.vo,com.example.seckill.bean,com.example.seckill.vo,com.example.seckill.vo
  #指定myBatis的核心配置文件与Mapper映射文件
  mapper-locations: classpath*:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true


server:
  error:
    whitelabel:
      enabled: false
